'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { X, ArrowUpRight } from 'lucide-react';
import PaymentService from '@/services/payment.service';
import { useAuth } from '@/context/AuthContext';
interface Props { course: { id:string; title:string; price:number }; onClose:()=>void; onSuccess?:()=>void }
export default function PaymentModal({course,onClose}:Props) {
 const {user}=useAuth(); const router=useRouter(); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const start=async()=>{if(!user){router.push('/login');return;}setLoading(true);setError('');try{const result=await PaymentService.createPayment(course.id);if(!result.success||!result.order?.id||!result.order?.approvalUrl)throw Error(result.message||'PayPal checkout is unavailable.');const approval=new URL(result.order.approvalUrl);if(approval.protocol!=='https:'||!/(^|\.)paypal\.com$/.test(approval.hostname))throw Error('Unexpected checkout destination.');sessionStorage.setItem('skillarious-paypal-order',JSON.stringify({orderId:result.order.id,courseId:course.id}));window.location.assign(approval.toString());}catch(e:any){setError(e?.response?.data?.message||e?.message||'Checkout could not be started.');setLoading(false)}};
 return <div className="fixed inset-0 z-[80] bg-black/70 flex items-center justify-center p-4" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="studio-card w-full max-w-md p-7 shadow-xl" role="dialog" aria-modal="true" aria-labelledby="checkout-title"><div className="flex justify-between items-start"><p className="eyebrow">Secure checkout</p><button aria-label="Close checkout" onClick={onClose}><X size={20}/></button></div><h2 className="text-3xl mt-4" id="checkout-title">Continue with PayPal</h2><p className="mt-5 text-[var(--muted-ink)]">{course.title}</p><p className="text-3xl font-serif my-6">${Number(course.price).toFixed(2)} <span className="text-sm font-sans">USD</span></p><p className="text-sm text-[var(--muted-ink)] mb-6">You will be redirected to PayPal Sandbox. Access is granted only after payment is verified on your return.</p>{error&&<p role="alert" className="mb-4 text-red-700">{error}</p>}<button className="studio-button w-full" disabled={loading} onClick={start}>{loading?'Preparing checkout…':'Continue to PayPal'} <ArrowUpRight size={17}/></button></div></div>;
}
