'use client';
import { Suspense, useEffect, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import courseService from '@/services/course.service';
import categoryService from '@/services/category.service';
import type { Course, Category } from '@/types';
import StudioCourseCard from '@/components/StudioCourseCard';
import CourseFinder from '@/components/CourseFinder';
function Results(){const query=useSearchParams()?.get('q')?.trim()||'';const [courses,setCourses]=useState<Course[]>([]);const [categories,setCategories]=useState<Category[]>([]);const [state,setState]=useState<'idle'|'loading'|'ready'|'error'>('idle');useEffect(()=>{if(!query){setState('idle');return}let active=true;setState('loading');Promise.all([courseService.searchCourses(query),categoryService.searchCategories(query)]).then(([c,cat])=>{if(!active)return;if(c.success===false||cat.success===false)throw Error('Search failed');setCourses(c.courses||[]);setCategories(cat.data||[]);setState('ready')}).catch(()=>{if(active)setState('error')});return()=>{active=false}},[query]);return <div className="shell page-section"><p className="eyebrow mb-5">Explore / Search</p><h1 className="editorial-title mb-6">{query?<>Results for <em>{query}</em></>:'Find your next subject.'}</h1><CourseFinder/>{state==='loading'?<p role="status">Searching the collection…</p>:state==='error'?<div className="studio-card p-8" role="alert"><h2 className="text-2xl">Search is unavailable.</h2><p className="text-[var(--muted-ink)] mt-2">Please try again when the catalog is reachable.</p></div>:state==='idle'?<p className="lede">Search for a topic or use the course finder above.</p>:<>{categories.length>0&&<section className="mb-10"><h2 className="text-3xl mb-5">Subjects</h2><div className="flex flex-wrap gap-3">{categories.map(category=><Link key={category.id} href={`/category/${category.id}`} className="studio-card px-5 py-4 font-semibold">{category.name} ↗</Link>)}</div></section>}{courses.length>0?<section><h2 className="text-3xl mb-5">Courses</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">{courses.map((course,i)=><StudioCourseCard key={course.id} course={course} index={i}/>)}</div></section>:categories.length===0?<p className="studio-card p-8">No matching courses or subjects. Try another phrase.</p>:null}</>}</div>}
export default function SearchPage(){return <Suspense fallback={<div className="shell page-section" role="status">Loading search…</div>}><Results/></Suspense>}
