import Link from 'next/link';
import { ArrowUpRight, BookOpen, Code2, PenTool, Star } from 'lucide-react';

const courses = [
  { name: 'Interfaces with intention', skill: 'Product design', teacher: 'Maya Chen', score: '4.9', reviews: 84, Icon: PenTool, color: '#d9dfc5', details: 'Bring hierarchy, typography and thoughtful interaction to your next interface.' },
  { name: 'Think in Python', skill: 'Development', teacher: 'Alex Rivera', score: '4.8', reviews: 126, Icon: Code2, color: '#e8d3b5', details: 'From your first function to a small, useful project you can call your own.' },
  { name: 'Statistics, made human', skill: 'Data & research', teacher: 'Nora James', score: '4.7', reviews: 62, Icon: BookOpen, color: '#c6d9d5', details: 'Find the story behind the numbers, with practical examples and clear notes.' },
];
export default function DemoPage() {
  return <div className="shell page-section"><p className="eyebrow">A glimpse of the studio</p><h1 className="editorial-title mt-5">Picture your next chapter.</h1><p className="lede mt-6">A sample collection to explore the new look. These courses, educators and reviews are illustrative—not real listings or purchases.</p><div className="grid md:grid-cols-3 gap-6 mt-12">{courses.map(({ name, skill, teacher, score, reviews, Icon, color, details }, index) => <article className="studio-card overflow-hidden" key={name}><div className="h-48 p-7 flex justify-between items-end text-[#192820]" style={{ background: color }}><Icon size={64} strokeWidth={1}/><span className="font-serif text-6xl opacity-50">0{index + 1}</span></div><div className="p-6"><p className="eyebrow">{skill} / Sample</p><h2 className="text-3xl mt-4">{name}</h2><p className="text-sm mt-2 text-[var(--muted-ink)]">With {teacher}</p><p className="text-sm leading-relaxed mt-5">{details}</p><div className="mt-6 pt-5 border-t border-[var(--line)] flex gap-2 items-center text-sm"><Star size={14}/>{score} <span className="text-[var(--muted-ink)]">· {reviews} sample reviews</span></div></div></article>)}</div><div className="studio-card p-7 md:p-12 mt-10 grid md:grid-cols-2 gap-8"><div><p className="eyebrow">Learning, with company</p><h2 className="text-4xl mt-4">A better question changes everything.</h2><p className="text-[var(--muted-ink)] mt-4">In real courses, open your notes and ask the learning companion for an explanation. Each answer includes its learning sources, with a path back to your educator.</p></div><div className="bg-[var(--sage)] p-6"><p className="text-xs uppercase tracking-wider">Illustrative conversation · Not generated live</p><p className="font-semibold mt-5">What does a Python function return?</p><p className="leading-relaxed mt-3">A function can give a value back to its caller using <code>return</code>. Think of it as the result of the work it does. For example, a function that adds two numbers returns their sum.</p><p className="text-xs mt-5">Sample note / Functions &amp; return values</p></div></div><Link href="/courses" className="studio-button mt-9">Browse the real collection <ArrowUpRight size={18}/></Link></div>;
}
